metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "lmdb"
replication_factor = 1

rpc_bind_addr = "0.0.0.0:3901"
rpc_secret = "27d33756004c8353d5d21818961c4e3b3c0a62f65191f68987748bfc3a2eeff6"

[s3_api]
s3_region = "garage"
api_bind_addr = "0.0.0.0:3900"
root_domain = ".s3.garage.localhost"

[s3_web]
bind_addr = "0.0.0.0:3903"
root_domain = ".localhost"
index = "index.html"

[admin]
api_bind_addr = "0.0.0.0:3902"
admin_token = "garage_admin_token_change_me"
